---
- hosts: tag_app_{{ app }}
  gather_facts: false
  tasks:
    - name: get Hostname
      shell: hostname -f
      register: output
    - name: output Hostname
      debug: msg="{{ output.stdout }}"
